### ISSUE TITLE
which version of tensorflow do you use for training wave_my.pb?

### ISSUE THREAD

**Issue by satoshiSchubert** [ShaofengZou/Android-Style-Transfer#3]
i ve trained my model and pb model,and checked the input and output using test_pb_file.py, it worked and the result is the same to wave_my.pb. But when i deploy it into android project and download the app to my phone, i can't use my own model(it will flash and close when i touch the icon of the model). i'm not sure if it is because the version of tensorflow.

**Comment by ShaofengZou** [comment]
Hey:
    
    you may connect your phone to the Android Studio, and watch the log window (may be) to see the bug. That's may help to find out the problems.

  



祝好！

邹少锋
Shaofeng Zou
Institute of Microelectronics, Tsinghua University
Beijing, 100084, P.R. China
Tel : 19800311831
Email : zousf19@mails.tsinghua.edu.cn
 
From: ConneR
Date: 2020-09-07 17:59
To: ShaofengZou/Android-Tensorflow-Style-Transfer
CC: Subscribed
Subject: [ShaofengZou/Android-Tensorflow-Style-Transfer] which version of tensorflow do you use for training wave_my.pb? (#3)
i ve trained my model and pb model,and checked the input and output using test_pb_file.py, it worked and the result is the same to wave_my.pb. But when i deploy it into android project and download the app to my phone, i can't use my own model(it will flash and close when i touch the icon of the model). i'm not sure if it is because the version of tensorflow.

**Comment by satoshiSchubert** [comment]
不知道这能不能解决我的问题，但是还是十分感谢你的快速的回复！




祝好！

黄洪祥





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShaofengZou/Android-Tensorflow-Style-Transfer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月7日(星期一) 晚上10:06
收件人:&nbsp;"ShaofengZou/Android-Tensorflow-Style-Transfer"<Android-Tensorflow-Style-Transfer@noreply.github.com&gt;;
抄送:&nbsp;"黄洪祥"<1072058925@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ShaofengZou/Android-Tensorflow-Style-Transfer] which version of tensorflow do you use for training wave_my.pb? (#3)





 Hey: 
      
     you may connect your phone to the Android Studio, and watch the log window (may be) to see the bug. That's may help to find out the problems. 
 
    
 
 
 
 祝好！ 
 
 邹少锋 
 Shaofeng Zou 
 Institute of Microelectronics, Tsinghua University 
 Beijing, 100084, P.R. China 
 Tel : 19800311831 
 Email : zousf19@mails.tsinghua.edu.cn 
   
 From: ConneR 
 Date: 2020-09-07 17:59 
 To: ShaofengZou/Android-Tensorflow-Style-Transfer 
 CC: Subscribed 
 Subject: [ShaofengZou/Android-Tensorflow-Style-Transfer] which version of tensorflow do you use for training wave_my.pb? (#3) 
 i ve trained my model and pb model,and checked the input and output using test_pb_file.py, it worked and the result is the same to wave_my.pb. But when i deploy it into android project and download the app to my phone, i can't use my own model(it will flash and close when i touch the icon of the model). i'm not sure if it is because the version of tensorflow.
